### ISSUE TITLE
about can setup

### ISSUE THREAD

**Issue by jkzhao01** [yihuai-gao/arx5-sdk#11]
hello yihuai,

After connecting the arx arm with my laptop. i follow your CAN setups to find out the correct firmware type. I firstly run `ls /dev/ttyACM*`, the terminal outputs: "Unknown device "/dev/ttyACM*": No such file or directory", then i try the second option and run `ip a` and there is no `can*` interface. All the two options fail, what is the reason? I'm sure the connection is ok.

thank you very much!
![20240815-171057](https://github.com/user-attachments/assets/aeb97952-288a-4d8f-a290-ff1d48e4b443)

**Comment by yihuai-gao** [comment]
Hi jkzhao01, could you list all the /dev/ files and find whether there are any changes after plugging the adatper (should be ttyACM0,1,2 etc)? You can also take a picture of your CAN adapter and let me check whether there are any connection problems. In the worst case, you can order several other USB-CAN adapters and try them one by one. It is possible that some adapters are just broken (see other issues).

Additionally, I'll release the EtherCAT-CAN interface soon. You can have a try afterwards.

**Comment by yihuai-gao** [comment]
EtherCAT-CAN interface is ready

**Comment by jkzhao01** [comment]
hi yihuai, thank you for your quick reply! below is my hardware connection, so based on my connection and your updated readme, i should chose to the EtherCAT-CAN interface setup? not the USB-CAN interface, right? According to your latest `EtherCAT-CAN setup`, I run test scripts `python examples/test_joint_control.py X5 enx207bd2ee2ba9`but get the new error showing the in the picture.
![20240816-113129](https://github.com/user-attachments/assets/9f78623f-06e5-4660-97bf-fec764257e68)
![20240816-113708](https://github.com/user-attachments/assets/fe9b03b4-4928-4dec-99ba-53a84e264ae8)
![20240816-113759](https://github.com/user-attachments/assets/1308115a-28e3-47bb-ba56-a1673c3f3918)

**Comment by jkzhao01** [comment]
hi yihuai, the problem has been fixed. I pull the updated codes to local and rebuild it, then the arx robot moves. Thank you!
