### ISSUE TITLE
ERROR about the initialization of the ARX-X5 motors

### ISSUE THREAD

**Issue by bohaocheung** [yihuai-gao/arx5-sdk#9]
## Question Description
![2024-07-31 10-27-problem](https://github.com/user-attachments/assets/073e60c1-7c24-4295-8c59-5a4afb7174d6)

```python
python examples/test_joint_control.py X5 can0
```

Running the above code results the following error：
```
All motors are not initialized. Please check the connection or power of the arm.
```
Error: The initialization function of the Arx5JointController class in `src/app/joint_controller.cpp` reports the above error when calling _init_robot().

![Arx5JointController](https://github.com/user-attachments/assets/0c55f964-7886-42bd-b723-b7edeea798d8)

![_init_robot](https://github.com/user-attachments/assets/7610eaa4-32e0-4709-b5dd-ed95bafe85bd)

Wish to get your help. Thanks a lot!

**Comment by yihuai-gao** [comment]
Hi Bohao. This is usually because your robot arm is not properly connected. Please check the CAN bus setup process in README.md and attach a screenshot of your network interfaces (using `ip a`) to this issue.

**Comment by yihuai-gao** [comment]
If the setup procedure is done correctly, you will find a `can0` interface that is connected to the arm.

**Comment by bohaocheung** [comment]
Thanks for your reply! I find a `can0` interface indeed, but the trouble still exists. (SLCAN framework, sorry for not mentioning that)
![can0](https://github.com/user-attachments/assets/476f84d3-a25a-4b36-ac7c-bb843322f7bc)
In factly, I've tried using two slcan modules and got the same results.
(I have tested the official ARX5-sdk successfully.)

**Comment by yihuai-gao** [comment]
Thanks for your information. Have you run the following code every time you plug in the CAN adapter?

sudo udevadm trigger
sudo slcand -o -f -s8 /dev/arxcan0 can0 && sudo ifconfig can0 up

**Comment by zbh17** [comment]
Thanks for your reminding. I run the code every time I plug in the CAN adapter but still failed.

**Comment by yihuai-gao** [comment]
Hmmm this is weird. Maybe try to use a candlelight usb-can adapter?

**Comment by yihuai-gao** [comment]
or check the can bus wire (try swapping the + and - data wire)

**Comment by zbh17** [comment]
> or check the can bus wire (try swapping the + and - data wire)

hahaha，already tried that，but still thanks!

**Comment by zbh17** [comment]
> Hmmm this is weird. Maybe try to use a candlelight usb-can adapter?

Yeah, I'll try that!

**Comment by yihuai-gao** [comment]
Is the candlelight framework working? Btw, I'm writing code for the original EtherCAT-CAN adapter. If you have time you can contact me via yihuai@stanford.edu and we can have a chat.

**Comment by bohaocheung** [comment]
> Is the candlelight framework working? Btw, I'm writing code for the original EtherCAT-CAN adapter. If you have time you can contact me via [yihuai@stanford.edu](mailto:yihuai@stanford.edu) and we can have a chat.

Thanks very much! I just got a candleligtht framework and tried it successfully!!! So nice of you!!

**Comment by JohnYao93** [comment]
Hi! I'm currently having this same exact issue; only I don't have access currently to a candlelight-compatible board. Was there some sort of update or solution since this post? Thanks!
